### ISSUE TITLE
Team Search Algorithm

### ISSUE THREAD

**Issue by MrFlark** [MrFlark/mentormaps#1]
Range
Skills
What Program (FLL/FTC/FRC)
How old the team is ←  option available only to mentors
How many years experience in program ← option only available to teams
Default - List all teams

**Comment by itsjustjon** [comment]
Range - Needs work
Skills - Works
What Program - Works

Replace 
"How old team" is and "how many years experience" with an "Are you a rookie team?" option -> Just check to see if Year started is the current year, maybe? Or just have a check box if it's a team's rookie year or not. Might not be necessary.

**Comment by MrFlark** [comment]
need to finish distance formula finder

**Comment by MrFlark** [comment]
see new issue: https://github.com/MrFlark/mentormaps/issues/34
