### ISSUE TITLE
Firefox compatibility issues

### ISSUE THREAD

**Issue by MrFlark** [MrFlark/mentormaps#104]
see #95

**Comment by MrFlark** [comment]
@itsjustjon does this relate specifically to Firefox ESR or Firefox in general? I know the early javascript caused some errors when the passwords were only numbers, but it seems like Firefox ESR is the only one with major graphical issues (Even IE8 works).

**Comment by itsjustjon** [comment]
It only refers to ESR

**Comment by MrFlark** [comment]
@itsjustjon so close the issue then? this has been discussed.

**Comment by itsjustjon** [comment]
Yes, also i released mentormaps
