### ISSUE TITLE
Can I sign up as both mentor and team

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#109]
Seems like once I sign up as a mentor, I cannot sign up as a team. I would like to do both

**Comment by itsjustjon** [comment]
Hi Mr. Sisk,

You cannot use the same email account for any two profiles on MentorMaps.
This was added in order to prevent duplicate accounts in the database.

Thanks,
Jon

**Comment by MrFlark** [comment]
refer to #116 for further updates on this matter
