### ISSUE TITLE
Different colored pins for FLL, FTC, FRC, & VEX

### ISSUE THREAD

**Issue by MrFlark** [MrFlark/mentormaps#11]

**Comment by itsjustjon** [comment]
Red pin: FRC Teams
White pin: FTC Team
Blue pin: FLL Team
(To be added later) Orange pin: VEX Team

**Comment by MrFlark** [comment]
finished everything but VEX pins

**Comment by MrFlark** [comment]
added legend div

**Comment by MrFlark** [comment]
not for vex, make a different issue
