### ISSUE TITLE
I see my own team flagged on the map when signed in as my team

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#111]
When I am logged in as my team, I should not see a flag on the map for my team

**Comment by itsjustjon** [comment]
Hi Mr. Sisk,

So, you are logged in as your own team and you are viewing your own flag
that is marking your own team, correct?

If so, that is there to mark your location so that you can easily tell
other mentors/teams in relation to you.

Thanks,
Jon Logrippo
