### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#112]
Logged in as team 2493. Team Info at bottom of page appears to have three images with broken links.

![image](https://cloud.githubusercontent.com/assets/4390828/9735499/1ca86f4e-55f0-11e5-9f7e-2e12ceea35c5.png)

**Comment by itsjustjon** [comment]
Hi Mr. Sisk,

We will look into that issue later today.

Those images are the different *FIRST* Program Logos/VEX Logos which appear
depending on what type of team you are.

Thanks,
Jon Logrippo
