### ISSUE TITLE
List of email addresses returned in HTML stream

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#113]
Using Chrome, on the TEAM landing page, I notice there is a list of email address and whether they are verified or not is in the HTML stream. email address harvesters would grab a lot of validated emails

![image](https://cloud.githubusercontent.com/assets/4390828/9735515/46a6f98c-55f0-11e5-8db8-18ec1861b4e5.png)

**Comment by MrFlark** [comment]
fixed as of 554f73d
