### ISSUE TITLE
Error when Editing Profile

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#114]
When editing my Mentor profile, I briefly see this error before redirecting to the Edit Profile page

![image](https://cloud.githubusercontent.com/assets/4390828/9735537/6ebb4efa-55f0-11e5-9caf-5dd1183f408e.png)

**Comment by itsjustjon** [comment]
Hi Mr. Sisk,

We will look into this issue later today.

Thanks for sniffing out the bugs,
Jon Logrippo

**Comment by MrFlark** [comment]
fixed as of a837cb9
