### ISSUE TITLE
Name appears twice on Unbiased MAP

### ISSUE THREAD

**Issue by rsisk101** [MrFlark/mentormaps#115]
Clicked on Unbiased Map from the menu and see my name listed twice on the maps. Not sure why.

![image](https://cloud.githubusercontent.com/assets/4390828/9735559/971e36be-55f0-11e5-9c18-e096599abf9b.png)

**Comment by itsjustjon** [comment]
Hi Mr. Sisk,

That's strange, not sure why that is occurring either.

We will look into that bug later today.

Thanks again for your help,
Jon Logrippo
