### ISSUE TITLE
Two Stages of Interest for Teams and Mentors

### ISSUE THREAD

**Issue by itsjustjon** [MrFlark/mentormaps#119]
Instead of just checking off teams and them getting an email notification, we should only have the "I'm Interested" checkbox put the team/mentor-of-interest into a person's dashboard. Then, when someone makes an official decision about which mentor/team they really want, they click a "Notify this team/mentor of my existence and make them aware of my interest for their team/mentor"

**Comment by MrFlark** [comment]
still needs work, but i've laid out the basic framework
