### ISSUE TITLE
Browser Support for Browsers Besides Chrome

### ISSUE THREAD

**Issue by itsjustjon** [MrFlark/mentormaps#121]
Known Browsers to Support:
- Firefox ESR (Boeing's work browser, and Boeing is where a majority of mentors come from)
-Internet Explorer 10+ (Just in case we have users who fall outside the realm of Chrome and Firefox)

**Comment by MrFlark** [comment]
IE9+ is supported thanks to some custom JS libraries and we already discussed the decision not to support Firefox ESR.
