### ISSUE TITLE
Mentormaps App?

### ISSUE THREAD

**Issue by MrFlark** [MrFlark/mentormaps#133]
maybe an app would be a worthy investment considering the site might not have a very high traffic retention rate.

**Comment by itsjustjon** [comment]
That has been considered previously and I am fine with developing one later
on down the road.

**Comment by TheMkrage** [comment]
I am totally down. It would have to be before build season.

**Comment by MrFlark** [comment]
@itsjustjon @TheMkrage parse is a prerequisite in this case, see #132 
I could do the Android version while Krager does iOS.
Can you give me a start date for build season? February, right?

**Comment by itsjustjon** [comment]
January 9th

**Comment by TheMkrage** [comment]
Kenny no wants.
