### ISSUE TITLE
Use different icons for mentors vs teams to clarify display

### ISSUE THREAD

**Issue by jetengr** [MrFlark/mentormaps#52]
When viewing the map, if you make mentor icons different from team icons, it might help clarify which view you are in.  it might be just my perspective as a testor, but it seems a bit confusing.

**Comment by MrFlark** [comment]
already done, a marker for a mentor would be the respective affiliate program color with an "M" in the center

see
![blue](https://cloud.githubusercontent.com/assets/6569482/9296222/7378a55c-443c-11e5-80f0-13201a667387.png)

as opposed to

![bluem](https://cloud.githubusercontent.com/assets/6569482/9296224/7c3e9282-443c-11e5-8b6a-609610267e1c.png)
