### ISSUE TITLE
account moderation system?

### ISSUE THREAD

**Issue by MrFlark** [MrFlark/mentormaps#90]
to avoid spam

**Comment by itsjustjon** [comment]
Sounds good to me. How to implement?

**Comment by MrFlark** [comment]
basically just create a system that doesn't let a user display on the map until approved by a moderator.

**Comment by itsjustjon** [comment]
Sounds like an account verification system.

**Comment by MrFlark** [comment]
except it'd prevent spam.
each account would hypothetically have to go through a personal approval process.

**Comment by MrFlark** [comment]
any thoughts? this might make it too slow or too much of a hassle.

**Comment by itsjustjon** [comment]
It might not be worth it if its too hard to do.

Can we do without it and launch tomorrow?
